name: Python version check
on: push

jobs:
    python-version-check-on-windows:
        name: python version check
        runs-on: windows-latest
        steps:
            - name: ver check
              run: python --version
