name: Python version check
on: push

jobs:
    python-version-check-on-windows:
        name: python version check
        runs-on: windows-latest
        steps:
            - name: ver check
              run: python --version

    python-version-check-on-linux:
        name: python version check
        runs-on: ubuntu-latest
        steps:
            - name: ver check
              run: python --version


    python-version-check-on-macos:
        name: python version check
        runs-on: macos-latest
        steps:
            - name: ver check
              run: python --version
